name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          # This will automatically use the AWS credentials provided in the GitHub Secrets
          # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY must be set in the repository secrets
          
      - name: Build and push Docker image
        run: |
          docker buildx build --file Dockerfile --tag ${{ secrets.ECR_REPOSITORY }}:$GITHUB_SHA --push .
        env:
          # Ensure the AWS credentials are available for Docker to use
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      # - name: Deploy to ECS
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      #   with:
      #     task-definition: ecs-task-definition.json
      #     service: your-ecs-service-name
      #     cluster: your-ecs-cluster-name
      #     wait-for-service-stability: true

      # - name: Run Integration Tests
      #   run: |
      #     # Replace with your integration testing commands
      #     curl -f http://your-application-url/health || exit 1

      # - name: Rollback on Failure
      #   if: failure()
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      #   with:
      #     task-definition: ecs-task-definition.json
      #     service: your-ecs-service-name
      #     cluster: your-ecs-cluster-name
      #     wait-for-service-stability: true
      #     rollback: true
